name: Build ColorPlus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: List repository structure (debug)
        shell: powershell
        run: |
          Write-Host "Repository structure:"
          Get-ChildItem -Recurse | Select-Object FullName | ForEach-Object { Write-Host $_.FullName }
          
      - name: Find solution and project files
        shell: powershell
        run: |
          # Buscar archivos .sln
          $slnFiles = Get-ChildItem -Path . -Filter *.sln -Recurse
          Write-Host "Found .sln files:"
          $slnFiles | ForEach-Object { Write-Host "  $($_.FullName)" }
          
          # Buscar archivos .csproj
          $csprojFiles = Get-ChildItem -Path . -Filter *.csproj -Recurse
          Write-Host "Found .csproj files:"
          $csprojFiles | ForEach-Object { Write-Host "  $($_.FullName)" }
          
          # Determinar qué compilar
          if ($slnFiles.Count -gt 0) {
            $buildTarget = $slnFiles[0].FullName
            Write-Host "Will build solution: $buildTarget"
          } elseif ($csprojFiles.Count -gt 0) {
            $buildTarget = $csprojFiles[0].FullName
            Write-Host "Will build project: $buildTarget"
          } else {
            Write-Error "No .sln or .csproj files found!"
            exit 1
          }
          
          # Guardar la ruta para los siguientes steps
          $buildTarget | Out-File -FilePath "build-target.txt" -Encoding utf8
          
      - name: Restore NuGet packages
        shell: powershell
        run: |
          $buildTarget = Get-Content "build-target.txt"
          Write-Host "Restoring packages for: $buildTarget"
          
          if ($buildTarget.EndsWith(".sln")) {
            nuget restore $buildTarget
          } else {
            nuget restore $buildTarget
          }
          
      - name: Build project
        shell: powershell
        run: |
          $buildTarget = Get-Content "build-target.txt"
          Write-Host "Building: $buildTarget"
          
          # Configurar para que PowerShell trate errores de MSBuild como excepciones
          $ErrorActionPreference = "Stop"
          
          # Intentar con diferentes configuraciones de plataforma
          $buildSucceeded = $false
          
          # Primer intento: Release|Any CPU (basado en tu .sln)
          try {
            Write-Host "Trying build with Configuration=Release Platform='Any CPU'..."
            msbuild $buildTarget /p:Configuration=Release /p:Platform="Any CPU" /m
            $buildSucceeded = $true
            Write-Host "Build succeeded with Any CPU platform"
          } catch {
            Write-Host "Any CPU build failed: $($_.Exception.Message)"
          }
          
          # Segundo intento: Solo Release sin especificar Platform
          if (-not $buildSucceeded) {
            try {
              Write-Host "Trying build with Configuration=Release (no platform specified)..."
              msbuild $buildTarget /p:Configuration=Release /m
              $buildSucceeded = $true
              Write-Host "Build succeeded with default platform"
            } catch {
              Write-Host "Default platform build failed: $($_.Exception.Message)"
            }
          }
          
          # Tercer intento: x64 por si acaso
          if (-not $buildSucceeded) {
            try {
              Write-Host "Trying build with Configuration=Release Platform=x64..."
              msbuild $buildTarget /p:Configuration=Release /p:Platform=x64 /m
              $buildSucceeded = $true
              Write-Host "Build succeeded with x64 platform"
            } catch {
              Write-Host "x64 platform build failed: $($_.Exception.Message)"
            }
          }
          
          if (-not $buildSucceeded) {
            Write-Error "All build attempts failed!"
            exit 1
          }
          
      - name: List all build outputs (debug)
        shell: powershell
        run: |
          Write-Host "Searching for build outputs..."
          Get-ChildItem -Path . -Recurse | Where-Object { 
            $_.Extension -eq ".gha" -or 
            $_.Extension -eq ".dll" -or 
            ($_.Directory.Name -eq "Release" -and $_.Extension -eq ".exe")
          } | ForEach-Object { 
            Write-Host "Found build output: $($_.FullName)" 
          }
          
      - name: Find and prepare .gha file
        shell: powershell
        run: |
          # Buscar archivo .gha
          $ghaFiles = Get-ChildItem -Path . -Filter "*.gha" -Recurse
          
          if ($ghaFiles.Count -eq 0) {
            Write-Host "No .gha file found directly. Looking for DLL files that might be renamed..."
            
            # Buscar en carpetas de Release
            $releaseDlls = Get-ChildItem -Path . -Recurse | Where-Object { 
              $_.Extension -eq ".dll" -and 
              $_.Directory.Name -eq "Release" -and
              $_.Name -like "*ColorPlus*"
            }
            
            if ($releaseDlls.Count -gt 0) {
              $sourceDll = $releaseDlls[0]
              Write-Host "Found DLL to convert: $($sourceDll.FullName)"
              
              # Crear directorio release
              New-Item -ItemType Directory -Force -Path ".\release"
              
              # Copiar DLL como .gha
              $targetPath = ".\release\ColorPlus.gha"
              Copy-Item $sourceDll.FullName $targetPath
              Write-Host "Copied DLL as GHA: $targetPath"
            } else {
              Write-Error "No suitable files found for .gha creation"
              exit 1
            }
          } else {
            Write-Host "Found .gha file: $($ghaFiles[0].FullName)"
            # Crear directorio release
            New-Item -ItemType Directory -Force -Path ".\release"
            # Copiar archivo .gha
            Copy-Item $ghaFiles[0].FullName ".\release\ColorPlus.gha"
            Write-Host "Copied .gha file to release directory"
          }
          
      - name: Upload .gha artifact
        uses: actions/upload-artifact@v4
        with:
          name: ColorPlus-gha
          path: ./release/ColorPlus.gha
          retention-days: 30
