name: Build ColorPlus GHA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Install .NET Framework 4.5.2 Developer Pack
      run: |
        Write-Host "Downloading .NET Framework 4.5.2 Developer Pack..."
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/4/3/B/43B61315-B2CE-4F5B-9E32-34CCA07B2F0E/NDP452-KB2901951-x86-x64-DevPack.exe" -OutFile "NDP452-KB2901951-x86-x64-DevPack.exe"
        Write-Host "Installing .NET Framework 4.5.2 Developer Pack..."
        Start-Process -FilePath "NDP452-KB2901951-x86-x64-DevPack.exe" -ArgumentList "/quiet", "/norestart" -Wait
        Write-Host "Installation completed."
      
    - name: Restore NuGet packages
      working-directory: ColorPlus
      run: nuget restore ColorPlus.sln
      
    - name: Build solution
      working-directory: ColorPlus
      run: msbuild ColorPlus.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Upload artifact .gha
      uses: actions/upload-artifact@v4
      with:
        name: ColorPlus-Plugin
        path: ColorPlus/bin/ColorPlus.gha
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ColorPlus/bin/ColorPlus.gha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
