name: Build ColorPlus GHA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Update target framework to 4.8
      working-directory: ColorPlus
      run: |
        (Get-Content ColorPlus.csproj) -replace '<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>' | Set-Content ColorPlus.csproj
        Write-Host "Updated target framework from v4.5 to v4.8"
      
    - name: Restore NuGet packages
      working-directory: ColorPlus
      run: nuget restore ColorPlus.sln
      
    - name: Build solution
      working-directory: ColorPlus
      run: msbuild ColorPlus.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Upload artifact .gha
      uses: actions/upload-artifact@v4
      with:
        name: ColorPlus-Plugin
        path: ColorPlus/bin/ColorPlus.gha
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ColorPlus/bin/ColorPlus.gha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
