name: Build ColorPlus Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List project files
      run: |
        echo "=== Project structure ==="
        dir
        echo "=== Looking for solution/project files ==="
        if (Test-Path "*.sln") { dir *.sln } else { echo "No .sln files found" }
        if (Test-Path "*.csproj") { dir *.csproj } else { echo "No .csproj files found" }
        
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Download Rhino/Grasshopper References
      run: |
        echo "Creating lib directory for references..."
        mkdir lib -ErrorAction SilentlyContinue
        
        # Nota: Aquí necesitarías subir las DLLs de referencia a tu repo
        # O usar una fuente alternativa de las DLLs
        echo "You need to add RhinoCommon.dll, Grasshopper.dll, and GH_IO.dll to a 'lib' folder"
        
    - name: Try to build (will fail without proper references)
      run: |
        if (Test-Path "ColorPlus.sln") {
          echo "Building solution..."
          msbuild ColorPlus.sln /p:Configuration=Release /p:Platform="Any CPU" /p:WarningLevel=0
        } elseif (Test-Path "ColorPlus.csproj") {
          echo "Building project..."
          msbuild ColorPlus.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:WarningLevel=0
        } else {
          echo "No build file found!"
          exit 1
        }
