name: Build ColorPlus for Grasshopper

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - name: Restore NuGet packages
      run: nuget restore ColorPlus.sln
      
    - name: Build solution
      run: msbuild ColorPlus.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Find and copy .gha file
      run: |
        # Buscar el archivo .gha generado
        $ghaFile = Get-ChildItem -Recurse -Filter "*.gha" | Select-Object -First 1
        if ($ghaFile) {
          Write-Host "Archivo .gha encontrado: $($ghaFile.FullName)"
          # Crear directorio para artifacts si no existe
          New-Item -ItemType Directory -Force -Path ".\release"
          # Copiar el archivo .gha al directorio release
          Copy-Item $ghaFile.FullName ".\release\ColorPlus.gha"
          Write-Host "Archivo copiado a: .\release\ColorPlus.gha"
        } else {
          Write-Host "No se encontró archivo .gha"
          exit 1
        }
      shell: powershell
      
    - name: Upload .gha artifact
      uses: actions/upload-artifact@v4
      with:
        name: ColorPlus-gha
        path: ./release/ColorPlus.gha
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/ColorPlus.gha
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
